parameters:
    models: Old-WeightC-MF
    rank: [10]
    iter: 100
    batch_size: [128]
    lambda: [0.1]
    lambda2: [0]
    confidence: [0]
    step: [0]
    alpha: [0]
    mode: 'none'
    topK: [5, 10, 15, 20, 50]
    metric: [NLL, AUC]