parameters:
    models: MF
    rank: [10]
    iter: 200
    batch_size: [128, 64, 32]
    lambda: [0.1, 0.01, 0.001, 0.0001, 0.00001]
    lambda2: [0]
    confidence: [0]
    step: [0]
    alpha: [0]
    mode: 'none'
    topK: [5, 10, 15, 20, 50]
    metric: [NLL, AUC]
